export const themeJson = {
  "themeName": "default",
  "colorPalette": "dark",
  "isPanelless": false,
  "backgroundImage": "https://api.surveyjs.io/private/Surveys/files?name=1d4fbea3-59f8-4f29-be97-3e764d2539a0",
  "backgroundOpacity": 1,
  "backgroundImageAttachment": "scroll",
  "backgroundImageFit": "cover",
  "cssVariables": {
    "--sjs-questionpanel-backcolor": "rgba(74, 74, 74, 1)",
    "--sjs-questionpanel-hovercolor": "rgba(74, 74, 74, 1)",
    "--sjs-font-family": "Quicksand, sans-serif",
    "--sjs-corner-radius": "10px",
    "--sjs-base-unit": "8px",
    "--sjs-font-pagetitle-family": "Quicksand, sans-serif",
    "--sjs-font-pagetitle-color": "rgba(91, 230, 121, 1)",
    "--sjs-font-pagedescription-family": "Quicksand, sans-serif",
    "--sjs-shadow-small": "0px 2px 0px 2px rgba(64, 64, 64, 1), 0px 0px 0px 2px rgba(64, 64, 64, 1)",
    "--sjs-font-questiontitle-family": "Quicksand, sans-serif",
    "--sjs-font-questiontitle-size": "18px",
    "--sjs-font-questiondescription-family": "Quicksand, sans-serif",
    "--sjs-font-questiondescription-size": "18px",
    "--sjs-shadow-inner": "0px 0px 0px 2px rgba(64, 64, 64, 1), 0px 2px 0px 2px rgba(64, 64, 64, 1)",
    "--sjs-font-editorfont-family": "Quicksand, sans-serif",
    "--sjs-border-default": "rgba(255, 255, 255, 0.12)",
    "--sjs-border-light": "rgba(255, 255, 255, 0.08)",
    "--sjs-general-backcolor": "rgba(48, 48, 48, 1)",
    "--sjs-general-backcolor-dark": "rgba(52, 52, 52, 1)",
    "--sjs-general-backcolor-dim-light": "rgba(43, 43, 43, 1)",
    "--sjs-general-backcolor-dim-dark": "rgba(46, 46, 46, 1)",
    "--sjs-general-forecolor": "rgba(255, 255, 255, 0.78)",
    "--sjs-general-forecolor-light": "rgba(255, 255, 255, 0.42)",
    "--sjs-general-dim-forecolor": "rgba(255, 255, 255, 0.79)",
    "--sjs-general-dim-forecolor-light": "rgba(255, 255, 255, 0.45)",
    "--sjs-secondary-backcolor": "rgba(255, 152, 20, 1)",
    "--sjs-secondary-backcolor-light": "rgba(255, 152, 20, 0.1)",
    "--sjs-secondary-backcolor-semi-light": "rgba(255, 152, 20, 0.25)",
    "--sjs-secondary-forecolor": "rgba(48, 48, 48, 1)",
    "--sjs-secondary-forecolor-light": "rgba(48, 48, 48, 0.25)",
    "--sjs-shadow-small-reset": "0px 0px 0px 0px rgba(64, 64, 64, 1), 0px 0px 0px 0px rgba(64, 64, 64, 1)",
    "--sjs-shadow-medium": "0px 2px 6px 0px rgba(0, 0, 0, 0.2)",
    "--sjs-shadow-large": "0px 8px 16px 0px rgba(0, 0, 0, 0.2)",
    "--sjs-shadow-inner-reset": "0px 0px 0px 0px rgba(64, 64, 64, 1), 0px 0px 0px 0px rgba(64, 64, 64, 1)",
    "--sjs-border-inside": "rgba(255, 255, 255, 0.08)",
    "--sjs-special-red-forecolor": "rgba(48, 48, 48, 1)",
    "--sjs-special-green": "rgba(36, 197, 164, 1)",
    "--sjs-special-green-light": "rgba(36, 197, 164, 0.1)",
    "--sjs-special-green-forecolor": "rgba(48, 48, 48, 1)",
    "--sjs-special-blue": "rgba(91, 151, 242, 1)",
    "--sjs-special-blue-light": "rgba(91, 151, 242, 0.1)",
    "--sjs-special-blue-forecolor": "rgba(48, 48, 48, 1)",
    "--sjs-special-yellow": "rgba(255, 152, 20, 1)",
    "--sjs-special-yellow-light": "rgba(255, 152, 20, 0.1)",
    "--sjs-special-yellow-forecolor": "rgba(48, 48, 48, 1)",
    "--sjs-article-font-xx-large-textDecoration": "none",
    "--sjs-article-font-xx-large-fontWeight": "700",
    "--sjs-article-font-xx-large-fontStyle": "normal",
    "--sjs-article-font-xx-large-fontStretch": "normal",
    "--sjs-article-font-xx-large-letterSpacing": "0",
    "--sjs-article-font-xx-large-lineHeight": "64px",
    "--sjs-article-font-xx-large-paragraphIndent": "0px",
    "--sjs-article-font-xx-large-textCase": "none",
    "--sjs-article-font-x-large-textDecoration": "none",
    "--sjs-article-font-x-large-fontWeight": "700",
    "--sjs-article-font-x-large-fontStyle": "normal",
    "--sjs-article-font-x-large-fontStretch": "normal",
    "--sjs-article-font-x-large-letterSpacing": "0",
    "--sjs-article-font-x-large-lineHeight": "56px",
    "--sjs-article-font-x-large-paragraphIndent": "0px",
    "--sjs-article-font-x-large-textCase": "none",
    "--sjs-article-font-large-textDecoration": "none",
    "--sjs-article-font-large-fontWeight": "700",
    "--sjs-article-font-large-fontStyle": "normal",
    "--sjs-article-font-large-fontStretch": "normal",
    "--sjs-article-font-large-letterSpacing": "0",
    "--sjs-article-font-large-lineHeight": "40px",
    "--sjs-article-font-large-paragraphIndent": "0px",
    "--sjs-article-font-large-textCase": "none",
    "--sjs-article-font-medium-textDecoration": "none",
    "--sjs-article-font-medium-fontWeight": "700",
    "--sjs-article-font-medium-fontStyle": "normal",
    "--sjs-article-font-medium-fontStretch": "normal",
    "--sjs-article-font-medium-letterSpacing": "0",
    "--sjs-article-font-medium-lineHeight": "32px",
    "--sjs-article-font-medium-paragraphIndent": "0px",
    "--sjs-article-font-medium-textCase": "none",
    "--sjs-article-font-default-textDecoration": "none",
    "--sjs-article-font-default-fontWeight": "400",
    "--sjs-article-font-default-fontStyle": "normal",
    "--sjs-article-font-default-fontStretch": "normal",
    "--sjs-article-font-default-letterSpacing": "0",
    "--sjs-article-font-default-lineHeight": "28px",
    "--sjs-article-font-default-paragraphIndent": "0px",
    "--sjs-article-font-default-textCase": "none",
    "--sjs-general-backcolor-dim": "#45a559",
    "--sjs-primary-backcolor": "#5be678",
    "--sjs-primary-backcolor-dark": "rgba(91, 230, 120, 1)",
    "--sjs-primary-backcolor-light": "rgba(91, 230, 120, 0.07)",
    "--sjs-primary-forecolor": "rgba(32, 32, 32, 1)",
    "--sjs-primary-forecolor-light": "rgba(32, 32, 32, 0.25)",
    "--sjs-special-red": "rgba(238, 43, 43, 1)",
    "--sjs-special-red-light": "rgba(238, 43, 43, 0.1)",
    "--sjs-font-headertitle-family": "Quicksand, sans-serif",
    "--sjs-font-headertitle-size": "50px",
    "--sjs-font-headertitle-color": "rgba(233, 230, 45, 1)",
    "--sjs-font-headerdescription-family": "Quicksand, sans-serif",
    "--sjs-font-headerdescription-size": "25px",
    "--sjs-font-headerdescription-color": "rgba(13, 32, 17, 0.7)",
    "--sjs-header-backcolor": "#45a559"
  },
  "header": {
    "height": 200,
    "textAreaWidth": 800,
    "overlapEnabled": true,
    "logoPositionY": "middle",
    "titlePositionY": "middle",
    "descriptionPositionY": "middle"
  },
  "headerView": "advanced"
}
